// let 3nome = 'teste1';
let nome3 = 'teste1';
let $nome = 'teste2';
let _nome = 'teste3';
// let @nome = 'teste3';
// let !nome = 'teste3';
let Nome = 'teste4';
let seuNome = 'teste5';
let seu_nome = 'teste6';
